### ISSUE TITLE
Can u add requirements.txt plz?

### ISSUE THREAD

**Issue by animemoeus** [tegal1337/NekoBotV1#5]
![Screenshot_20200220_235338](https://user-images.githubusercontent.com/33395829/74953219-5b9ce000-543c-11ea-9d23-4509799f0831.png)

**Comment by l3tm3** [comment]
first use python 2.7
import sys, os, re, socket, binascii, time, json, random, threading, Queue, pprint, urlparse, smtplib, telnetlib, os.path, hashlib, string, urllib2, glob, sqlite3, urllib, argparse, marshal, base64, requests
from colorama import *
from random import choice
from colorama import Fore, Back, init
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from platform import system
from Queue import Queue
from time import strftime
from urlparse import urlparse
from urllib2 import urlopen
